# coding: utf-8

"""
    app.salesflare.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from salesflare.models.tasks_post200_response import TasksPost200Response

class TestTasksPost200Response(unittest.TestCase):
    """TasksPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TasksPost200Response:
        """Test TasksPost200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TasksPost200Response`
        """
        model = TasksPost200Response()
        if include_optional:
            return TasksPost200Response(
                id = 56
            )
        else:
            return TasksPost200Response(
                id = 56,
        )
        """

    def testTasksPost200Response(self):
        """Test TasksPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
