# coding: utf-8

"""
    app.salesflare.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from salesflare.models.tasks_get200_response_inner_email import TasksGet200ResponseInnerEmail

class TestTasksGet200ResponseInnerEmail(unittest.TestCase):
    """TasksGet200ResponseInnerEmail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TasksGet200ResponseInnerEmail:
        """Test TasksGet200ResponseInnerEmail
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TasksGet200ResponseInnerEmail`
        """
        model = TasksGet200ResponseInnerEmail()
        if include_optional:
            return TasksGet200ResponseInnerEmail(
                id = None,
                email_message_id = None,
                service_message_id = None,
                data_source = None,
                subject = None
            )
        else:
            return TasksGet200ResponseInnerEmail(
                id = None,
                email_message_id = None,
                service_message_id = None,
                data_source = None,
                subject = None,
        )
        """

    def testTasksGet200ResponseInnerEmail(self):
        """Test TasksGet200ResponseInnerEmail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
