# coding: utf-8

"""
    app.salesflare.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from salesflare.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_messenger_web_metrics_post(self) -> None:
        """Test case for messenger_web_metrics_post

        /messenger/web/metrics
        """
        pass

    def test_tasks_get(self) -> None:
        """Test case for tasks_get

        /tasks
        """
        pass

    def test_tasks_post(self) -> None:
        """Test case for tasks_post

        /tasks
        """
        pass

    def test_v1_m_post(self) -> None:
        """Test case for v1_m_post

        /v1/m
        """
        pass


if __name__ == '__main__':
    unittest.main()
