# coding: utf-8

"""
    app.salesflare.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from salesflare.models.tasks_get200_response_inner_account import TasksGet200ResponseInnerAccount

class TestTasksGet200ResponseInnerAccount(unittest.TestCase):
    """TasksGet200ResponseInnerAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TasksGet200ResponseInnerAccount:
        """Test TasksGet200ResponseInnerAccount
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TasksGet200ResponseInnerAccount`
        """
        model = TasksGet200ResponseInnerAccount()
        if include_optional:
            return TasksGet200ResponseInnerAccount(
                id = 56,
                name = '',
                picture = ''
            )
        else:
            return TasksGet200ResponseInnerAccount(
                id = 56,
                name = '',
                picture = '',
        )
        """

    def testTasksGet200ResponseInnerAccount(self):
        """Test TasksGet200ResponseInnerAccount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
