# coding: utf-8

"""
    app.salesflare.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from salesflare.models.v1_m_post200_response import V1MPost200Response

class TestV1MPost200Response(unittest.TestCase):
    """V1MPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1MPost200Response:
        """Test V1MPost200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1MPost200Response`
        """
        model = V1MPost200Response()
        if include_optional:
            return V1MPost200Response(
                success = True
            )
        else:
            return V1MPost200Response(
                success = True,
        )
        """

    def testV1MPost200Response(self):
        """Test V1MPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
