=begin
#app.salesflare.com

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/tasks_get200_response_inner'
require 'openapi_client/models/tasks_get200_response_inner_account'
require 'openapi_client/models/tasks_get200_response_inner_assignees_inner'
require 'openapi_client/models/tasks_get200_response_inner_email'
require 'openapi_client/models/tasks_get200_response_inner_email_any_of'
require 'openapi_client/models/tasks_post200_response'
require 'openapi_client/models/v1_m_post200_response'

# APIs
require 'openapi_client/api/default_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
