/*
 * app.salesflare.com
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.TasksGet200ResponseInnerEmailAnyOf;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import org.openapitools.client.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-21T01:27:30.481182-07:00[America/Los_Angeles]")
public class TasksGet200ResponseInnerEmail extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(TasksGet200ResponseInnerEmail.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!TasksGet200ResponseInnerEmail.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'TasksGet200ResponseInnerEmail' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<Object> adapterObject = gson.getDelegateAdapter(this, TypeToken.get(Object.class));
            final TypeAdapter<TasksGet200ResponseInnerEmailAnyOf> adapterTasksGet200ResponseInnerEmailAnyOf = gson.getDelegateAdapter(this, TypeToken.get(TasksGet200ResponseInnerEmailAnyOf.class));

            return (TypeAdapter<T>) new TypeAdapter<TasksGet200ResponseInnerEmail>() {
                @Override
                public void write(JsonWriter out, TasksGet200ResponseInnerEmail value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `Object`
                    if (value.getActualInstance() instanceof Object) {
                      JsonPrimitive primitive = adapterObject.toJsonTree((Object)value.getActualInstance()).getAsJsonPrimitive();
                      elementAdapter.write(out, primitive);
                      return;
                    }
                    // check if the actual instance is of the type `TasksGet200ResponseInnerEmailAnyOf`
                    if (value.getActualInstance() instanceof TasksGet200ResponseInnerEmailAnyOf) {
                      JsonElement element = adapterTasksGet200ResponseInnerEmailAnyOf.toJsonTree((TasksGet200ResponseInnerEmailAnyOf)value.getActualInstance());
                      elementAdapter.write(out, element);
                      return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match anyOf schemae: Object, TasksGet200ResponseInnerEmailAnyOf");
                }

                @Override
                public TasksGet200ResponseInnerEmail read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize Object
                    try {
                      // validate the JSON object to see if any exception is thrown
                      if(!jsonElement.getAsJsonPrimitive().isNumber()) {
                        throw new IllegalArgumentException(String.format("Expected json element to be of type Number in the JSON string but got `%s`", jsonElement.toString()));
                      }
                      actualAdapter = adapterObject;
                      TasksGet200ResponseInnerEmail ret = new TasksGet200ResponseInnerEmail();
                      ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                      return ret;
                    } catch (Exception e) {
                      // deserialization failed, continue
                      errorMessages.add(String.format("Deserialization for Object failed with `%s`.", e.getMessage()));
                      log.log(Level.FINER, "Input data does not match schema 'Object'", e);
                    }
                    // deserialize TasksGet200ResponseInnerEmailAnyOf
                    try {
                      // validate the JSON object to see if any exception is thrown
                      TasksGet200ResponseInnerEmailAnyOf.validateJsonElement(jsonElement);
                      actualAdapter = adapterTasksGet200ResponseInnerEmailAnyOf;
                      TasksGet200ResponseInnerEmail ret = new TasksGet200ResponseInnerEmail();
                      ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                      return ret;
                    } catch (Exception e) {
                      // deserialization failed, continue
                      errorMessages.add(String.format("Deserialization for TasksGet200ResponseInnerEmailAnyOf failed with `%s`.", e.getMessage()));
                      log.log(Level.FINER, "Input data does not match schema 'TasksGet200ResponseInnerEmailAnyOf'", e);
                    }

                    throw new IOException(String.format("Failed deserialization for TasksGet200ResponseInnerEmail: no class matches result, expected at least 1. Detailed failure message for anyOf schemas: %s. JSON: %s", errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in anyOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public TasksGet200ResponseInnerEmail() {
        super("anyOf", Boolean.FALSE);
    }

    public TasksGet200ResponseInnerEmail(Object o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public TasksGet200ResponseInnerEmail(TasksGet200ResponseInnerEmailAnyOf o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("Object", Object.class);
        schemas.put("TasksGet200ResponseInnerEmailAnyOf", TasksGet200ResponseInnerEmailAnyOf.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return TasksGet200ResponseInnerEmail.schemas;
    }

    /**
     * Set the instance that matches the anyOf child schema, check
     * the instance parameter is valid against the anyOf child schemas:
     * Object, TasksGet200ResponseInnerEmailAnyOf
     *
     * It could be an instance of the 'anyOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof Object) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof TasksGet200ResponseInnerEmailAnyOf) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be Object, TasksGet200ResponseInnerEmailAnyOf");
    }

    /**
     * Get the actual instance, which can be the following:
     * Object, TasksGet200ResponseInnerEmailAnyOf
     *
     * @return The actual instance (Object, TasksGet200ResponseInnerEmailAnyOf)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `Object`. If the actual instance is not `Object`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Object`
     * @throws ClassCastException if the instance is not `Object`
     */
    public Object getObject() throws ClassCastException {
        return (Object)super.getActualInstance();
    }
    /**
     * Get the actual instance of `TasksGet200ResponseInnerEmailAnyOf`. If the actual instance is not `TasksGet200ResponseInnerEmailAnyOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `TasksGet200ResponseInnerEmailAnyOf`
     * @throws ClassCastException if the instance is not `TasksGet200ResponseInnerEmailAnyOf`
     */
    public TasksGet200ResponseInnerEmailAnyOf getTasksGet200ResponseInnerEmailAnyOf() throws ClassCastException {
        return (TasksGet200ResponseInnerEmailAnyOf)super.getActualInstance();
    }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to TasksGet200ResponseInnerEmail
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    // validate anyOf schemas one by one
    ArrayList<String> errorMessages = new ArrayList<>();
    // validate the json string with Object
    try {
      if(!jsonElement.getAsJsonPrimitive().isNumber()) {
        throw new IllegalArgumentException(String.format("Expected json element to be of type Number in the JSON string but got `%s`", jsonElement.toString()));
      }
      return;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for Object failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    // validate the json string with TasksGet200ResponseInnerEmailAnyOf
    try {
      TasksGet200ResponseInnerEmailAnyOf.validateJsonElement(jsonElement);
      return;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for TasksGet200ResponseInnerEmailAnyOf failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    throw new IOException(String.format("The JSON string is invalid for TasksGet200ResponseInnerEmail with anyOf schemas: Object, TasksGet200ResponseInnerEmailAnyOf. no class match the result, expected at least 1. Detailed failure message for anyOf schemas: %s. JSON: %s", errorMessages, jsonElement.toString()));
    
  }

 /**
  * Create an instance of TasksGet200ResponseInnerEmail given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TasksGet200ResponseInnerEmail
  * @throws IOException if the JSON string is invalid with respect to TasksGet200ResponseInnerEmail
  */
  public static TasksGet200ResponseInnerEmail fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TasksGet200ResponseInnerEmail.class);
  }

 /**
  * Convert an instance of TasksGet200ResponseInnerEmail to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

