=begin
#app.salesflare.com

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::DefaultApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::DefaultApi)
    end
  end

  # unit tests for messenger_web_metrics_post
  # /messenger/web/metrics
  # **Host**: http://api-iam.intercom.io
  # @param app_id 
  # @param v 
  # @param g 
  # @param s 
  # @param r 
  # @param platform 
  # @param installation_type 
  # @param idempotency_key 
  # @param internal 
  # @param is_intersection_booted 
  # @param page_title 
  # @param user_active_company_id 
  # @param metrics 
  # @param logs 
  # @param op_metrics 
  # @param hc_metrics 
  # @param referer 
  # @param anonymous_session 
  # @param device_identifier 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'messenger_web_metrics_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for tasks_get
  # /tasks
  # **Host**: http://api.salesflare.com
  # @param [Hash] opts the optional parameters
  # @option opts [String] :limit 
  # @option opts [String] :q 
  # @return [Array<TasksGet200ResponseInner>]
  describe 'tasks_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for tasks_post
  # /tasks
  # **Host**: http://api.salesflare.com
  # @param [Hash] opts the optional parameters
  # @return [TasksPost200Response]
  describe 'tasks_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_m_post
  # /v1/m
  # **Host**: http://api.segment.io
  # @param [Hash] opts the optional parameters
  # @return [V1MPost200Response]
  describe 'v1_m_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
