/*
app.salesflare.com

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package salesflare

import (
	"encoding/json"
	"fmt"
)

// TasksGet200ResponseInnerEmail struct for TasksGet200ResponseInnerEmail
type TasksGet200ResponseInnerEmail struct {
	TasksGet200ResponseInnerEmailAnyOf *TasksGet200ResponseInnerEmailAnyOf
	interface{} *interface{}
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *TasksGet200ResponseInnerEmail) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into TasksGet200ResponseInnerEmailAnyOf
	err = json.Unmarshal(data, &dst.TasksGet200ResponseInnerEmailAnyOf);
	if err == nil {
		jsonTasksGet200ResponseInnerEmailAnyOf, _ := json.Marshal(dst.TasksGet200ResponseInnerEmailAnyOf)
		if string(jsonTasksGet200ResponseInnerEmailAnyOf) == "{}" { // empty struct
			dst.TasksGet200ResponseInnerEmailAnyOf = nil
		} else {
			return nil // data stored in dst.TasksGet200ResponseInnerEmailAnyOf, return on the first match
		}
	} else {
		dst.TasksGet200ResponseInnerEmailAnyOf = nil
	}

	// try to unmarshal JSON data into interface{}
	err = json.Unmarshal(data, &dst.interface{});
	if err == nil {
		jsoninterface{}, _ := json.Marshal(dst.interface{})
		if string(jsoninterface{}) == "{}" { // empty struct
			dst.interface{} = nil
		} else {
			return nil // data stored in dst.interface{}, return on the first match
		}
	} else {
		dst.interface{} = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(TasksGet200ResponseInnerEmail)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *TasksGet200ResponseInnerEmail) MarshalJSON() ([]byte, error) {
	if src.TasksGet200ResponseInnerEmailAnyOf != nil {
		return json.Marshal(&src.TasksGet200ResponseInnerEmailAnyOf)
	}

	if src.interface{} != nil {
		return json.Marshal(&src.interface{})
	}

	return nil, nil // no data in anyOf schemas
}

type NullableTasksGet200ResponseInnerEmail struct {
	value *TasksGet200ResponseInnerEmail
	isSet bool
}

func (v NullableTasksGet200ResponseInnerEmail) Get() *TasksGet200ResponseInnerEmail {
	return v.value
}

func (v *NullableTasksGet200ResponseInnerEmail) Set(val *TasksGet200ResponseInnerEmail) {
	v.value = val
	v.isSet = true
}

func (v NullableTasksGet200ResponseInnerEmail) IsSet() bool {
	return v.isSet
}

func (v *NullableTasksGet200ResponseInnerEmail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTasksGet200ResponseInnerEmail(val *TasksGet200ResponseInnerEmail) *NullableTasksGet200ResponseInnerEmail {
	return &NullableTasksGet200ResponseInnerEmail{value: val, isSet: true}
}

func (v NullableTasksGet200ResponseInnerEmail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTasksGet200ResponseInnerEmail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


