/*
app.salesflare.com

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package salesflare

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TasksPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TasksPost200Response{}

// TasksPost200Response struct for TasksPost200Response
type TasksPost200Response struct {
	Id int32 `json:"id"`
}

type _TasksPost200Response TasksPost200Response

// NewTasksPost200Response instantiates a new TasksPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTasksPost200Response(id int32) *TasksPost200Response {
	this := TasksPost200Response{}
	this.Id = id
	return &this
}

// NewTasksPost200ResponseWithDefaults instantiates a new TasksPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTasksPost200ResponseWithDefaults() *TasksPost200Response {
	this := TasksPost200Response{}
	return &this
}

// GetId returns the Id field value
func (o *TasksPost200Response) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TasksPost200Response) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TasksPost200Response) SetId(v int32) {
	o.Id = v
}

func (o TasksPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TasksPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *TasksPost200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTasksPost200Response := _TasksPost200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTasksPost200Response)

	if err != nil {
		return err
	}

	*o = TasksPost200Response(varTasksPost200Response)

	return err
}

type NullableTasksPost200Response struct {
	value *TasksPost200Response
	isSet bool
}

func (v NullableTasksPost200Response) Get() *TasksPost200Response {
	return v.value
}

func (v *NullableTasksPost200Response) Set(val *TasksPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableTasksPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableTasksPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTasksPost200Response(val *TasksPost200Response) *NullableTasksPost200Response {
	return &NullableTasksPost200Response{value: val, isSet: true}
}

func (v NullableTasksPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTasksPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


