/*
app.salesflare.com

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package salesflare

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TasksGet200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TasksGet200ResponseInner{}

// TasksGet200ResponseInner struct for TasksGet200ResponseInner
type TasksGet200ResponseInner struct {
	Id int32 `json:"id"`
	Type string `json:"type"`
	Account TasksGet200ResponseInnerAccount `json:"account"`
	Creator NullableInt32 `json:"creator"`
	Description string `json:"description"`
	ReminderDate string `json:"reminder_date"`
	Email TasksGet200ResponseInnerEmail `json:"email"`
	Company interface{} `json:"company"`
	Meeting interface{} `json:"meeting"`
	Completed bool `json:"completed"`
	CompletionDate interface{} `json:"completion_date"`
	Completor interface{} `json:"completor"`
	Archived bool `json:"archived"`
	ArchiveDate interface{} `json:"archive_date"`
	Archivor interface{} `json:"archivor"`
	LastModifiedBy NullableInt32 `json:"last_modified_by"`
	CreationDate string `json:"creation_date"`
	ModificationDate string `json:"modification_date"`
	Assignees []TasksGet200ResponseInnerAssigneesInner `json:"assignees"`
	CanEdit bool `json:"can_edit"`
}

type _TasksGet200ResponseInner TasksGet200ResponseInner

// NewTasksGet200ResponseInner instantiates a new TasksGet200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTasksGet200ResponseInner(id int32, type_ string, account TasksGet200ResponseInnerAccount, creator NullableInt32, description string, reminderDate string, email TasksGet200ResponseInnerEmail, company interface{}, meeting interface{}, completed bool, completionDate interface{}, completor interface{}, archived bool, archiveDate interface{}, archivor interface{}, lastModifiedBy NullableInt32, creationDate string, modificationDate string, assignees []TasksGet200ResponseInnerAssigneesInner, canEdit bool) *TasksGet200ResponseInner {
	this := TasksGet200ResponseInner{}
	this.Id = id
	this.Type = type_
	this.Account = account
	this.Creator = creator
	this.Description = description
	this.ReminderDate = reminderDate
	this.Email = email
	this.Company = company
	this.Meeting = meeting
	this.Completed = completed
	this.CompletionDate = completionDate
	this.Completor = completor
	this.Archived = archived
	this.ArchiveDate = archiveDate
	this.Archivor = archivor
	this.LastModifiedBy = lastModifiedBy
	this.CreationDate = creationDate
	this.ModificationDate = modificationDate
	this.Assignees = assignees
	this.CanEdit = canEdit
	return &this
}

// NewTasksGet200ResponseInnerWithDefaults instantiates a new TasksGet200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTasksGet200ResponseInnerWithDefaults() *TasksGet200ResponseInner {
	this := TasksGet200ResponseInner{}
	return &this
}

// GetId returns the Id field value
func (o *TasksGet200ResponseInner) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TasksGet200ResponseInner) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TasksGet200ResponseInner) SetId(v int32) {
	o.Id = v
}

// GetType returns the Type field value
func (o *TasksGet200ResponseInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TasksGet200ResponseInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TasksGet200ResponseInner) SetType(v string) {
	o.Type = v
}

// GetAccount returns the Account field value
func (o *TasksGet200ResponseInner) GetAccount() TasksGet200ResponseInnerAccount {
	if o == nil {
		var ret TasksGet200ResponseInnerAccount
		return ret
	}

	return o.Account
}

// GetAccountOk returns a tuple with the Account field value
// and a boolean to check if the value has been set.
func (o *TasksGet200ResponseInner) GetAccountOk() (*TasksGet200ResponseInnerAccount, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Account, true
}

// SetAccount sets field value
func (o *TasksGet200ResponseInner) SetAccount(v TasksGet200ResponseInnerAccount) {
	o.Account = v
}

// GetCreator returns the Creator field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *TasksGet200ResponseInner) GetCreator() int32 {
	if o == nil || o.Creator.Get() == nil {
		var ret int32
		return ret
	}

	return *o.Creator.Get()
}

// GetCreatorOk returns a tuple with the Creator field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TasksGet200ResponseInner) GetCreatorOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Creator.Get(), o.Creator.IsSet()
}

// SetCreator sets field value
func (o *TasksGet200ResponseInner) SetCreator(v int32) {
	o.Creator.Set(&v)
}

// GetDescription returns the Description field value
func (o *TasksGet200ResponseInner) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *TasksGet200ResponseInner) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *TasksGet200ResponseInner) SetDescription(v string) {
	o.Description = v
}

// GetReminderDate returns the ReminderDate field value
func (o *TasksGet200ResponseInner) GetReminderDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReminderDate
}

// GetReminderDateOk returns a tuple with the ReminderDate field value
// and a boolean to check if the value has been set.
func (o *TasksGet200ResponseInner) GetReminderDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReminderDate, true
}

// SetReminderDate sets field value
func (o *TasksGet200ResponseInner) SetReminderDate(v string) {
	o.ReminderDate = v
}

// GetEmail returns the Email field value
func (o *TasksGet200ResponseInner) GetEmail() TasksGet200ResponseInnerEmail {
	if o == nil {
		var ret TasksGet200ResponseInnerEmail
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *TasksGet200ResponseInner) GetEmailOk() (*TasksGet200ResponseInnerEmail, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *TasksGet200ResponseInner) SetEmail(v TasksGet200ResponseInnerEmail) {
	o.Email = v
}

// GetCompany returns the Company field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *TasksGet200ResponseInner) GetCompany() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Company
}

// GetCompanyOk returns a tuple with the Company field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TasksGet200ResponseInner) GetCompanyOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Company) {
		return nil, false
	}
	return &o.Company, true
}

// SetCompany sets field value
func (o *TasksGet200ResponseInner) SetCompany(v interface{}) {
	o.Company = v
}

// GetMeeting returns the Meeting field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *TasksGet200ResponseInner) GetMeeting() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Meeting
}

// GetMeetingOk returns a tuple with the Meeting field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TasksGet200ResponseInner) GetMeetingOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Meeting) {
		return nil, false
	}
	return &o.Meeting, true
}

// SetMeeting sets field value
func (o *TasksGet200ResponseInner) SetMeeting(v interface{}) {
	o.Meeting = v
}

// GetCompleted returns the Completed field value
func (o *TasksGet200ResponseInner) GetCompleted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Completed
}

// GetCompletedOk returns a tuple with the Completed field value
// and a boolean to check if the value has been set.
func (o *TasksGet200ResponseInner) GetCompletedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Completed, true
}

// SetCompleted sets field value
func (o *TasksGet200ResponseInner) SetCompleted(v bool) {
	o.Completed = v
}

// GetCompletionDate returns the CompletionDate field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *TasksGet200ResponseInner) GetCompletionDate() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.CompletionDate
}

// GetCompletionDateOk returns a tuple with the CompletionDate field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TasksGet200ResponseInner) GetCompletionDateOk() (*interface{}, bool) {
	if o == nil || IsNil(o.CompletionDate) {
		return nil, false
	}
	return &o.CompletionDate, true
}

// SetCompletionDate sets field value
func (o *TasksGet200ResponseInner) SetCompletionDate(v interface{}) {
	o.CompletionDate = v
}

// GetCompletor returns the Completor field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *TasksGet200ResponseInner) GetCompletor() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Completor
}

// GetCompletorOk returns a tuple with the Completor field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TasksGet200ResponseInner) GetCompletorOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Completor) {
		return nil, false
	}
	return &o.Completor, true
}

// SetCompletor sets field value
func (o *TasksGet200ResponseInner) SetCompletor(v interface{}) {
	o.Completor = v
}

// GetArchived returns the Archived field value
func (o *TasksGet200ResponseInner) GetArchived() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Archived
}

// GetArchivedOk returns a tuple with the Archived field value
// and a boolean to check if the value has been set.
func (o *TasksGet200ResponseInner) GetArchivedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Archived, true
}

// SetArchived sets field value
func (o *TasksGet200ResponseInner) SetArchived(v bool) {
	o.Archived = v
}

// GetArchiveDate returns the ArchiveDate field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *TasksGet200ResponseInner) GetArchiveDate() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.ArchiveDate
}

// GetArchiveDateOk returns a tuple with the ArchiveDate field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TasksGet200ResponseInner) GetArchiveDateOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ArchiveDate) {
		return nil, false
	}
	return &o.ArchiveDate, true
}

// SetArchiveDate sets field value
func (o *TasksGet200ResponseInner) SetArchiveDate(v interface{}) {
	o.ArchiveDate = v
}

// GetArchivor returns the Archivor field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *TasksGet200ResponseInner) GetArchivor() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Archivor
}

// GetArchivorOk returns a tuple with the Archivor field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TasksGet200ResponseInner) GetArchivorOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Archivor) {
		return nil, false
	}
	return &o.Archivor, true
}

// SetArchivor sets field value
func (o *TasksGet200ResponseInner) SetArchivor(v interface{}) {
	o.Archivor = v
}

// GetLastModifiedBy returns the LastModifiedBy field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *TasksGet200ResponseInner) GetLastModifiedBy() int32 {
	if o == nil || o.LastModifiedBy.Get() == nil {
		var ret int32
		return ret
	}

	return *o.LastModifiedBy.Get()
}

// GetLastModifiedByOk returns a tuple with the LastModifiedBy field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TasksGet200ResponseInner) GetLastModifiedByOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastModifiedBy.Get(), o.LastModifiedBy.IsSet()
}

// SetLastModifiedBy sets field value
func (o *TasksGet200ResponseInner) SetLastModifiedBy(v int32) {
	o.LastModifiedBy.Set(&v)
}

// GetCreationDate returns the CreationDate field value
func (o *TasksGet200ResponseInner) GetCreationDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreationDate
}

// GetCreationDateOk returns a tuple with the CreationDate field value
// and a boolean to check if the value has been set.
func (o *TasksGet200ResponseInner) GetCreationDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreationDate, true
}

// SetCreationDate sets field value
func (o *TasksGet200ResponseInner) SetCreationDate(v string) {
	o.CreationDate = v
}

// GetModificationDate returns the ModificationDate field value
func (o *TasksGet200ResponseInner) GetModificationDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ModificationDate
}

// GetModificationDateOk returns a tuple with the ModificationDate field value
// and a boolean to check if the value has been set.
func (o *TasksGet200ResponseInner) GetModificationDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModificationDate, true
}

// SetModificationDate sets field value
func (o *TasksGet200ResponseInner) SetModificationDate(v string) {
	o.ModificationDate = v
}

// GetAssignees returns the Assignees field value
func (o *TasksGet200ResponseInner) GetAssignees() []TasksGet200ResponseInnerAssigneesInner {
	if o == nil {
		var ret []TasksGet200ResponseInnerAssigneesInner
		return ret
	}

	return o.Assignees
}

// GetAssigneesOk returns a tuple with the Assignees field value
// and a boolean to check if the value has been set.
func (o *TasksGet200ResponseInner) GetAssigneesOk() ([]TasksGet200ResponseInnerAssigneesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Assignees, true
}

// SetAssignees sets field value
func (o *TasksGet200ResponseInner) SetAssignees(v []TasksGet200ResponseInnerAssigneesInner) {
	o.Assignees = v
}

// GetCanEdit returns the CanEdit field value
func (o *TasksGet200ResponseInner) GetCanEdit() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanEdit
}

// GetCanEditOk returns a tuple with the CanEdit field value
// and a boolean to check if the value has been set.
func (o *TasksGet200ResponseInner) GetCanEditOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanEdit, true
}

// SetCanEdit sets field value
func (o *TasksGet200ResponseInner) SetCanEdit(v bool) {
	o.CanEdit = v
}

func (o TasksGet200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TasksGet200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["account"] = o.Account
	toSerialize["creator"] = o.Creator.Get()
	toSerialize["description"] = o.Description
	toSerialize["reminder_date"] = o.ReminderDate
	toSerialize["email"] = o.Email
	if o.Company != nil {
		toSerialize["company"] = o.Company
	}
	if o.Meeting != nil {
		toSerialize["meeting"] = o.Meeting
	}
	toSerialize["completed"] = o.Completed
	if o.CompletionDate != nil {
		toSerialize["completion_date"] = o.CompletionDate
	}
	if o.Completor != nil {
		toSerialize["completor"] = o.Completor
	}
	toSerialize["archived"] = o.Archived
	if o.ArchiveDate != nil {
		toSerialize["archive_date"] = o.ArchiveDate
	}
	if o.Archivor != nil {
		toSerialize["archivor"] = o.Archivor
	}
	toSerialize["last_modified_by"] = o.LastModifiedBy.Get()
	toSerialize["creation_date"] = o.CreationDate
	toSerialize["modification_date"] = o.ModificationDate
	toSerialize["assignees"] = o.Assignees
	toSerialize["can_edit"] = o.CanEdit
	return toSerialize, nil
}

func (o *TasksGet200ResponseInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"account",
		"creator",
		"description",
		"reminder_date",
		"email",
		"company",
		"meeting",
		"completed",
		"completion_date",
		"completor",
		"archived",
		"archive_date",
		"archivor",
		"last_modified_by",
		"creation_date",
		"modification_date",
		"assignees",
		"can_edit",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTasksGet200ResponseInner := _TasksGet200ResponseInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTasksGet200ResponseInner)

	if err != nil {
		return err
	}

	*o = TasksGet200ResponseInner(varTasksGet200ResponseInner)

	return err
}

type NullableTasksGet200ResponseInner struct {
	value *TasksGet200ResponseInner
	isSet bool
}

func (v NullableTasksGet200ResponseInner) Get() *TasksGet200ResponseInner {
	return v.value
}

func (v *NullableTasksGet200ResponseInner) Set(val *TasksGet200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableTasksGet200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableTasksGet200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTasksGet200ResponseInner(val *TasksGet200ResponseInner) *NullableTasksGet200ResponseInner {
	return &NullableTasksGet200ResponseInner{value: val, isSet: true}
}

func (v NullableTasksGet200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTasksGet200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


