/*
app.salesflare.com

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package salesflare

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TasksGet200ResponseInnerAccount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TasksGet200ResponseInnerAccount{}

// TasksGet200ResponseInnerAccount struct for TasksGet200ResponseInnerAccount
type TasksGet200ResponseInnerAccount struct {
	Id int32 `json:"id"`
	Name string `json:"name"`
	Picture string `json:"picture"`
}

type _TasksGet200ResponseInnerAccount TasksGet200ResponseInnerAccount

// NewTasksGet200ResponseInnerAccount instantiates a new TasksGet200ResponseInnerAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTasksGet200ResponseInnerAccount(id int32, name string, picture string) *TasksGet200ResponseInnerAccount {
	this := TasksGet200ResponseInnerAccount{}
	this.Id = id
	this.Name = name
	this.Picture = picture
	return &this
}

// NewTasksGet200ResponseInnerAccountWithDefaults instantiates a new TasksGet200ResponseInnerAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTasksGet200ResponseInnerAccountWithDefaults() *TasksGet200ResponseInnerAccount {
	this := TasksGet200ResponseInnerAccount{}
	return &this
}

// GetId returns the Id field value
func (o *TasksGet200ResponseInnerAccount) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TasksGet200ResponseInnerAccount) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TasksGet200ResponseInnerAccount) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *TasksGet200ResponseInnerAccount) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TasksGet200ResponseInnerAccount) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TasksGet200ResponseInnerAccount) SetName(v string) {
	o.Name = v
}

// GetPicture returns the Picture field value
func (o *TasksGet200ResponseInnerAccount) GetPicture() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Picture
}

// GetPictureOk returns a tuple with the Picture field value
// and a boolean to check if the value has been set.
func (o *TasksGet200ResponseInnerAccount) GetPictureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Picture, true
}

// SetPicture sets field value
func (o *TasksGet200ResponseInnerAccount) SetPicture(v string) {
	o.Picture = v
}

func (o TasksGet200ResponseInnerAccount) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TasksGet200ResponseInnerAccount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["picture"] = o.Picture
	return toSerialize, nil
}

func (o *TasksGet200ResponseInnerAccount) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"picture",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTasksGet200ResponseInnerAccount := _TasksGet200ResponseInnerAccount{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTasksGet200ResponseInnerAccount)

	if err != nil {
		return err
	}

	*o = TasksGet200ResponseInnerAccount(varTasksGet200ResponseInnerAccount)

	return err
}

type NullableTasksGet200ResponseInnerAccount struct {
	value *TasksGet200ResponseInnerAccount
	isSet bool
}

func (v NullableTasksGet200ResponseInnerAccount) Get() *TasksGet200ResponseInnerAccount {
	return v.value
}

func (v *NullableTasksGet200ResponseInnerAccount) Set(val *TasksGet200ResponseInnerAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableTasksGet200ResponseInnerAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableTasksGet200ResponseInnerAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTasksGet200ResponseInnerAccount(val *TasksGet200ResponseInnerAccount) *NullableTasksGet200ResponseInnerAccount {
	return &NullableTasksGet200ResponseInnerAccount{value: val, isSet: true}
}

func (v NullableTasksGet200ResponseInnerAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTasksGet200ResponseInnerAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


