//
// TasksGet200ResponseInnerEmailAnyOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TasksGet200ResponseInnerEmailAnyOf: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var emailMessageId: String
    public var serviceMessageId: String
    public var dataSource: Int
    public var subject: String

    public init(id: Int, emailMessageId: String, serviceMessageId: String, dataSource: Int, subject: String) {
        self.id = id
        self.emailMessageId = emailMessageId
        self.serviceMessageId = serviceMessageId
        self.dataSource = dataSource
        self.subject = subject
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case emailMessageId = "email_message_id"
        case serviceMessageId = "service_message_id"
        case dataSource = "data_source"
        case subject
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(emailMessageId, forKey: .emailMessageId)
        try container.encode(serviceMessageId, forKey: .serviceMessageId)
        try container.encode(dataSource, forKey: .dataSource)
        try container.encode(subject, forKey: .subject)
    }
}

