//
// TasksGet200ResponseInnerAccount.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TasksGet200ResponseInnerAccount: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var name: String
    public var picture: String

    public init(id: Int, name: String, picture: String) {
        self.id = id
        self.name = name
        self.picture = picture
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case picture
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(picture, forKey: .picture)
    }
}

