//
// TasksGet200ResponseInnerAssigneesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TasksGet200ResponseInnerAssigneesInner: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var email: String
    public var picture: String
    public var name: String
    public var disabled: Bool

    public init(id: Int, email: String, picture: String, name: String, disabled: Bool) {
        self.id = id
        self.email = email
        self.picture = picture
        self.name = name
        self.disabled = disabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case email
        case picture
        case name
        case disabled
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(email, forKey: .email)
        try container.encode(picture, forKey: .picture)
        try container.encode(name, forKey: .name)
        try container.encode(disabled, forKey: .disabled)
    }
}

