//
// TasksGet200ResponseInnerEmail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TasksGet200ResponseInnerEmail: Codable, JSONEncodable, Hashable {

    public var id: AnyCodable?
    public var emailMessageId: AnyCodable?
    public var serviceMessageId: AnyCodable?
    public var dataSource: AnyCodable?
    public var subject: AnyCodable?

    public init(id: AnyCodable?, emailMessageId: AnyCodable?, serviceMessageId: AnyCodable?, dataSource: AnyCodable?, subject: AnyCodable?) {
        self.id = id
        self.emailMessageId = emailMessageId
        self.serviceMessageId = serviceMessageId
        self.dataSource = dataSource
        self.subject = subject
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case emailMessageId = "email_message_id"
        case serviceMessageId = "service_message_id"
        case dataSource = "data_source"
        case subject
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(emailMessageId, forKey: .emailMessageId)
        try container.encode(serviceMessageId, forKey: .serviceMessageId)
        try container.encode(dataSource, forKey: .dataSource)
        try container.encode(subject, forKey: .subject)
    }
}

