/*
 * app.salesflare.com
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.TasksGet200ResponseInnerAccount;
import org.openapitools.client.model.TasksGet200ResponseInnerAssigneesInner;
import org.openapitools.client.model.TasksGet200ResponseInnerEmail;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TasksGet200ResponseInner
 */
public class TasksGet200ResponseInnerTest {
    private final TasksGet200ResponseInner model = new TasksGet200ResponseInner();

    /**
     * Model tests for TasksGet200ResponseInner
     */
    @Test
    public void testTasksGet200ResponseInner() {
        // TODO: test TasksGet200ResponseInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'account'
     */
    @Test
    public void accountTest() {
        // TODO: test account
    }

    /**
     * Test the property 'creator'
     */
    @Test
    public void creatorTest() {
        // TODO: test creator
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'reminderDate'
     */
    @Test
    public void reminderDateTest() {
        // TODO: test reminderDate
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'company'
     */
    @Test
    public void companyTest() {
        // TODO: test company
    }

    /**
     * Test the property 'meeting'
     */
    @Test
    public void meetingTest() {
        // TODO: test meeting
    }

    /**
     * Test the property 'completed'
     */
    @Test
    public void completedTest() {
        // TODO: test completed
    }

    /**
     * Test the property 'completionDate'
     */
    @Test
    public void completionDateTest() {
        // TODO: test completionDate
    }

    /**
     * Test the property 'completor'
     */
    @Test
    public void completorTest() {
        // TODO: test completor
    }

    /**
     * Test the property 'archived'
     */
    @Test
    public void archivedTest() {
        // TODO: test archived
    }

    /**
     * Test the property 'archiveDate'
     */
    @Test
    public void archiveDateTest() {
        // TODO: test archiveDate
    }

    /**
     * Test the property 'archivor'
     */
    @Test
    public void archivorTest() {
        // TODO: test archivor
    }

    /**
     * Test the property 'lastModifiedBy'
     */
    @Test
    public void lastModifiedByTest() {
        // TODO: test lastModifiedBy
    }

    /**
     * Test the property 'creationDate'
     */
    @Test
    public void creationDateTest() {
        // TODO: test creationDate
    }

    /**
     * Test the property 'modificationDate'
     */
    @Test
    public void modificationDateTest() {
        // TODO: test modificationDate
    }

    /**
     * Test the property 'assignees'
     */
    @Test
    public void assigneesTest() {
        // TODO: test assignees
    }

    /**
     * Test the property 'canEdit'
     */
    @Test
    public void canEditTest() {
        // TODO: test canEdit
    }

}
