/*
 * app.salesflare.com
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TasksGet200ResponseInnerEmailAnyOf
 */
public class TasksGet200ResponseInnerEmailAnyOfTest {
    private final TasksGet200ResponseInnerEmailAnyOf model = new TasksGet200ResponseInnerEmailAnyOf();

    /**
     * Model tests for TasksGet200ResponseInnerEmailAnyOf
     */
    @Test
    public void testTasksGet200ResponseInnerEmailAnyOf() {
        // TODO: test TasksGet200ResponseInnerEmailAnyOf
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'emailMessageId'
     */
    @Test
    public void emailMessageIdTest() {
        // TODO: test emailMessageId
    }

    /**
     * Test the property 'serviceMessageId'
     */
    @Test
    public void serviceMessageIdTest() {
        // TODO: test serviceMessageId
    }

    /**
     * Test the property 'dataSource'
     */
    @Test
    public void dataSourceTest() {
        // TODO: test dataSource
    }

    /**
     * Test the property 'subject'
     */
    @Test
    public void subjectTest() {
        // TODO: test subject
    }

}
