# coding: utf-8

# flake8: noqa
"""
    app.salesflare.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from salesflare.models.tasks_get200_response_inner import TasksGet200ResponseInner
from salesflare.models.tasks_get200_response_inner_account import TasksGet200ResponseInnerAccount
from salesflare.models.tasks_get200_response_inner_assignees_inner import TasksGet200ResponseInnerAssigneesInner
from salesflare.models.tasks_get200_response_inner_email import TasksGet200ResponseInnerEmail
from salesflare.models.tasks_get200_response_inner_email_any_of import TasksGet200ResponseInnerEmailAnyOf
from salesflare.models.tasks_post200_response import TasksPost200Response
from salesflare.models.v1_m_post200_response import V1MPost200Response
